# Generated by Django 2.2.28 on 2022-10-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressrofldjiawh'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressrofldjiawh',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
